# Generated by Django 3.0.8 on 2020-10-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_problem_share_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='accepted_number',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='io_mode',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='rule_type',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='share_submission',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='source',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='spj',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='spj_code',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='spj_compile_ok',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='spj_language',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='spj_version',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='statistic_info',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='submission_number',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='template',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='test_case_id',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='test_case_score',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='visible',
        ),
    ]
