# Generated by Django 3.0.8 on 2020-10-19 06:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_auto_20201013_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='languages',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=['C']),
        ),
    ]
