# Generated by Django 3.0.8 on 2020-10-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0017_auto_20201019_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='share_submission',
            field=models.BooleanField(default=False),
        ),
    ]
