# Generated by Django 3.0.8 on 2020-11-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0019_problem_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='submission_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
