# Generated by Django 3.0.8 on 2020-11-16 13:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0020_problem_submission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='accepted_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='statistic_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='problem',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
