# Generated by Django 3.0.8 on 2020-11-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0021_auto_20201116_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='rule_type',
            field=models.TextField(default='ACM'),
        ),
    ]
