# Generated by Django 3.0.8 on 2020-11-16 14:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import problem.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0022_problem_rule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.TextField(default='MID'),
        ),
        migrations.AddField(
            model_name='problem',
            name='io_mode',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=problem.models._default_io_mode),
        ),
        migrations.AddField(
            model_name='problem',
            name='source',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='spj',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='spj_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='spj_compile_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='spj_language',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='spj_version',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='template',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='problem',
            name='test_case_id',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='test_case_score',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
