# Generated by Django 3.0.8 on 2020-11-23 23:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0023_auto_20201116_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='test_case_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_case_score',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
